### ISSUE TITLE
sing and help command

### ISSUE THREAD

**Issue by TheDiscordHistorian** [Drapersniper/Audio#5]
When invoking the sing command, I get this error
```py
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/cogs/CogManager/cogs/audio/core/commands/miscellaneous.py", line 31, in command_sing
    await ctx.invoke(self.command_play, query=url)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 144, in invoke
    ret = await command.callback(*arguments, **kwargs)
TypeError: command_play() got an unexpected keyword argument 'query'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/cogs/Downloader/lib/jishaku/cog_base.py", line 345, in jsk_debug
    await alt_ctx.command.invoke(alt_ctx)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: command_play() got an unexpected keyword argument 'query'
```

And when doing `[p]help` while audio loaded, the command errors. I don't know if its a main bot issue or cog issue, so putting this also here.

```py
Exception in command 'help'
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/venv/lib/python3.8/site-packages/redbot/core/commands/help.py", line 870, in red_help
    await ctx.bot.send_help_for(ctx, thing_to_get_help_for, from_help_command=True)
  File "/data/venv/lib/python3.8/site-packages/redbot/core/bot.py", line 1405, in send_help_for
    return await self._help_formatter.send_help(
  File "/data/venv/lib/python3.8/site-packages/redbot/core/commands/help.py", line 223, in send_help
    await self.format_bot_help(ctx, help_settings=help_settings)
  File "/data/venv/lib/python3.8/site-packages/redbot/core/commands/help.py", line 627, in format_bot_help
    cog_text = "\n".join(
  File "/data/venv/lib/python3.8/site-packages/redbot/core/commands/help.py", line 628, in <genexpr>
    shorten_line(f"**{name}** {command.format_shortdoc_for_context(ctx)}")
  File "/data/venv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 701, in format_shortdoc_for_context
    sh = self.short_doc
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 982, in short_doc
    if self.help is not None:
  File "/data/venv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 398, in help
    return inspect.cleandoc(translator(command_doc))
TypeError: <lambda>() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: <lambda>() takes 1 positional argument but 2 were given```

**Comment by Drapersniper** [comment]
Has been fixed
